### ISSUE TITLE
Provide MobiFlight variables to store and read data without having to use FSUIPC or WASM Module

### ISSUE THREAD

**Issue by Mobiflight** [Mobiflight/MobiFlight-Connector#373]
## Problem summary

FSUIPC user offsets have been commonly used in MF for internal control of panel configurations.  MF should incorporate its own internal user defined variables to improve efficiency and speed of execution.

## MF Version

All versions.

## Steps to reproduce

* Today, any type of user defined value needs to be stored outside of MF, either in FSUIPC or more recently in MF wasm Lvars.
* Value then has to be pulled back into MF to be used in internal panel control causing this process to be slower than necessary.

## Expected result

Create a new data structure within Mobiflight to handle user defined variables.  It could be similar to the FSUIPC user offset \(which MF can already handle\), or similar to the Lvars used in the wasm \(“Mobiflight Variables”, a.k.a. “Mvars”\) which MF can also handle, but instead of sending the data out, the variables would be stored and managed internally.  This should result in a highly efficient and faster data storage and retrieval system for internal controls, than experienced so far with FSUIPC.

If needed, initial Mvar values could be stored in a xml file for later use.

## Further details

* I honestly think hex offset addresses are for programmers, not users, so I would favor the Mvar names instead.  User defined Mvar names would be more friendly.
* Currently, 64 bytes offsets \(0x66C0-66FF\) provided by FSUIPC, sounds very little to me.  Consider providing more space.

## Tasks
- [x] Add a Variable Cache Mechanism to MobiFlight Cache
- [x] Add an Output Type for MobiFlight Variables
- [x] Add an Input Type for MobiFlight Variables
- [x] Save and Load the config with MobiFlight Variable settings
- [x] ~~Auto Suggest Mechanism that suggests already defined MobiFlight variables~~ [moved to enhancement issue](https://github.com/Mobiflight/MobiFlight-Connector/issues/433)
- [x] Add UnitTests for config
- [x] Add UnitTests for InputAction
- [x] Add Localization for all Forms
- [x] Variables are reset when MF stops
- [x] Documentation [Sim Variable](https://github.com/Mobiflight/MobiFlight-Connector/wiki/Sim-Variables-%28for-Output%29#mobiflight-variable) [Input Action](https://github.com/Mobiflight/MobiFlight-Connector/wiki/Input-Actions#mobiflight-variable)

**Comment by Mobiflight** [comment]
- [ ] Add a Variable Cache Mechanism to MobiFlight Cache
- [ ] Add an Output Type for MobiFlight Variables
- [ ] Add an Input Type for MobiFlight Variables
- [ ] Save and Load the config with MobiFlight Variable settings
- [ ] Documentation
