### ISSUE TITLE
MobiFlight Community Feedback Feature - Telemetry Tracking

### ISSUE THREAD

**Issue by Mobiflight** [Mobiflight/MobiFlight-Connector#395]
As MobiFlight Developer I would love to have a better view on how users are actually using the software to focus on improving the areas that are used most.

To achieve this, we will introduce an opt-in usage reporting function.
- [x] Opt-In Message Displayed
- [x] Enabling and Disabling of Community feedback in Settings menu
- [x] Anonymized User Identifier
- [x] Number of MobiFlight Starts per User
- [x] MobiFlight Version (Start until End)
- [x] Duration of MobiFlight Session (Start until End)
- [x] MobiFlight Board Statistics (Number of Boards Connected, Firmware, Number of Devices per type)
- [x] Arcaze Board Statistics
- [x] Number of Output Configs
- [x] Number of Input Configs
- [x] Logging Mode Settings
- [x] Beta Updates Enabled
- [x] Flight Sim Type (FSX, MSFS2020, P3D, XPLANE)
- [x] Localization for Dialogs and Settings

**Comment by Mobiflight** [comment]
This feature has been implemented.
