### ISSUE TITLE
Dynamic Code Events via WASM Module

### ISSUE THREAD

**Issue by Mobiflight** [Mobiflight/MobiFlight-Connector#424]
**Is your feature request related to a problem? Please describe.**
At the moment we have to manage events in txt files and keep them in sync of each other. It would be great if one could simply define arbitrary code as input action.

**Describe the solution you'd like**
As a user I can define a code in MobiFlight that is executed when an Input Event occurs so that I don't have to add the custom event to events.user.txt and the other preset file which eventually will save me a lot of trouble and time.

**Describe alternatives you've considered**
None.

**Additional context**
I have to be able to reference Config References and respective Placeholders.

**Tasks**
- [x] Add Input Action Config
- [x] Add UI
- [x] Add Unit Tests
- [x] Add Documentation (https://github.com/Mobiflight/MobiFlight-Connector/wiki/Input-Actions#msfs2020---custom-input)

**Comment by Mobiflight** [comment]
A new input action "MSFS2020 - Custom Code" is available
