### ISSUE TITLE
UI not showing correctly for German Locale

### ISSUE THREAD

**Issue by MobiFlight-Admin** [MobiFlight/MobiFlight-Connector#473]
**Describe the bug**
When you choose German as UI Language, many dialogs in the config wizard dont look correctly.

**Steps To Reproduce**

1. Set UI Language to German
2. Open Config Wizard

**Expected behavior**
UI looks correct and all labels are readable

**Actual behavior**
UI doesnt look correct in all places.

**Tasks**
- [x] ConfigWizard - Source Type Label fixed
- [x] ConfigWizard - Config References (nimm) fixed
- [x] ConfigWizard - LED Module - missing German Translation
- [x] InputConfigWizard - Config References - missing Translation
- [x] InputConfigWizard - MobiFlight Variable - missing Translation
- [x] InputConfigWizard - FSUIPC Event ID - missing Translation / also Param is cut off
- [x] InputConfigWizard - FSUIPC PMDG Event ID - missing Translation / Custom Param Label is cut off, Mouse Param Drop Box too large
- [x] InputConfigWizard - MSS2020 Custom Input - missing Translation
- [x] InputConfigWizard - General - Placeholder hint text is not translated
