### ISSUE TITLE
WASM module events reload command 

### ISSUE THREAD

**Issue by JaimeLeon2** [MobiFlight/MobiFlight-Connector#474]
**Is your feature request related to a problem? Please describe.**
After SU5, the only way to have Msfs and the MF Wasm module adopt any changes made to the events.txt and events.user.txt files is by restarting the simulator. This process can take easily 10 minutes. 

**Describe the solution you'd like**
Create a special reserved event called "MF_WASM_EVENTS_RELOAD" that when received by the module causes the module to reload the events. This event can be triggered from a button in our panels, just like any other event (it would probably need to be included in events.txt), and from a button in the MF Connector UI. All this is external to the simulator, so it should not disturb the Sim, but if necessary, the special event could pause the Sim and unpause it at the end. 

**Describe alternatives you've considered**
The alternative is to use the Custom Input box, but this is only for MF Connector users. 

**Additional context**
I believe regular users will still prefer to use presets from events.txt rather than copying code to the custom input box. This new feature would make it easier to test new events already in events.user.txt format. 

**Tasks**
- [ ] Add reload option to MF menu
- [ ] Implement reload logic in WASM module
- [ ] Implement reload logic in MF Wasm Client

**Linked issue**
#396

**Comment by MobiFlight-Admin** [comment]
@JaimeLeon2 

I am thinking about this, in my opinion this is something that advanced users want to do when they are testing new events.
With the new custom code input you can do this testing until satisfied. Then you can add the event to hubhop and also to your events.user.txt.

The quick turnaround for the "developer" is now possible.

I wonder if the regular user also benefits from this functionality.

**Comment by DocMoebiuz** [comment]
I will close this since we now moved away from events.txt
